services:
  co-dm:
    build: .
    restart: "no"
    env_file: ./.env
    ports:
      - "3200:3200"
      - "3202:3202"
    volumes:
      - ./sessions:/app/sessions
      - ./cert.pem:/app/cert.pem:ro
      - ./key.pem:/app/key.pem:ro
      - ./config:/app/config
      - ./services/dashboard/public:/app/services/dashboard/public
      - ./services/player-bridge/public:/app/services/player-bridge/public
      - ./assets:/app/assets
