services:
  co-dm:
    build: .
    init: true
    stop_grace_period: 10s
    restart: "no"
    env_file: ./.env
    network_mode: host
    volumes:
      - ./sessions:/app/sessions
      - ./cert.pem:/app/cert.pem:ro
      - ./key.pem:/app/key.pem:ro
      - ./config:/app/config
      - ./services/dashboard/public:/app/services/dashboard/public
      - ./services/player-bridge/public:/app/services/player-bridge/public
      - ./assets:/app/assets
